#!/bin/bash

COMMAND="kagui"
APP_DATA="$HOME/.local/share/koopman-analysis-gui"

function setup() {
  if ! command -v python3 &> /dev/null; then
      echo "Python 3 is not installed. Please install Python 3 to run this application."
      exit 1
  fi

  if [ ! -d ".venv" ]; then
      echo "Creating virtual environment from $(python3 --version)"
      python3 -m venv .venv
  fi

  source .venv/bin/activate
  pip install --upgrade pip
  pip install -r requirements.txt
}

function usage() {
  echo "Usage: ${COMMAND} [run]"
  echo "  run   - Run the Koopman Analysis GUI application"
}

case "$1" in
  run)
    cd "$APP_DATA"
    if [ ! -d ".venv" ]; then
        echo "Setting up virtual environment..."
        setup
    fi
    source .venv/bin/activate
    python3 app/main.py
    ;;
  *)
    usage
    exit 1
    ;;
esac