from __future__ import annotations

MONITOR_FG = '#FFFFFF'
MONITOR_BG = '#1D1D1D'
SIDEBAR_FG = '#333333'
SIDEBAR_BG = '#F5F5F7'
ANALYSIS_BUTTON_FG = '#FFFFFF'
ANALYSIS_BUTTON_BG = '#005BB5'
ANALYSIS_BUTTON_ACTIVE_FG = '#FFFFFF'
ANALYSIS_BUTTON_ACTIVE_BG = '#003F8A'
GRAPH_BG = '#FFFFFF'